In [1]:
inputs = [1, 2, 3, 2.5]
weights = [0.2, 0.8, -0.5, 1]
bias = 2

output = (inputs[0] * weights[0]
           + inputs[1] * weights[1]
           + inputs[2] * weights[2]
           + inputs[3] * weights[3] 
           + bias)
print(output)

4.8


Layers from Scratch
- A crude example of a fully connected network i.e. all neurons have connections to every other neuron. This is opposed to sparsely connected networks, which neurons are not connected at every layer.


In [4]:
inputs = [1, 2, 3, 2.5]
weights1 = [0.2, 0.8, -0.5, 1]
weights2 = [.5, -.91, .26, -.5]
weights3 = [-.26, -.27, .17, .87]
bias1 = 2
bias2 = 3
bias3 = .5

output = [inputs[0] * weights1[0]
           + inputs[1] * weights1[1]
           + inputs[2] * weights1[2]
           + inputs[3] * weights1[3] + bias1,
           inputs[0] * weights2[0]
           + inputs[1] * weights2[1]
           + inputs[2] * weights2[2]
           + inputs[3] * weights2[3] + bias2,
           inputs[0] * weights3[0]
           + inputs[1] * weights3[1]
           + inputs[2] * weights3[2]
           + inputs[3] * weights3[3] + bias3,
           ]

print(output)

[4.8, 1.21, 2.385]


A More Dynamic Implementation
- iterate over the weights in biases using zip, in other words: for each neuron. Three sets of weights and three biases = 3 neurons
- integrate (add up) the output of the neuron over each weight times input then add the bias
- append each to the layer output list

In [1]:
inputs = [1, 2, 3, 2.5]
weights = [[0.2, 0.8, -0.5, 1],[0.5, -0.91, 0.26, -0.5],[-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, .5]

layer_outputs = []

for neuron_weights, neuron_bias in zip(weights, biases):
    neuron_output = 0
    for n_input, weight in zip(inputs, neuron_weights):
        neuron_output += n_input * weight
    neuron_output += neuron_bias
    layer_outputs.append(neuron_output)

print(layer_outputs)

[4.8, 1.21, 2.385]


Matrix, Array, Tensors
-Terms are used somewhat interchangeably when it comes to ML/AI
-Arrays are homologous - meaning for each row, the row length is identical, or for each column the column length is identical - this is along 2 dimensions. Generally, there must be consistency across dimensions
- Arrays defined as row count, column count : 3x2, (3,2) => 3 rows 2 columns
- Matrix is a subset of arrays => two dimensional homologous array.
- Determine array size of dimensions by counting the number of elements inside each braket (see example below)
- Tensors are not just arrays, but are represented as arrays for coding purposes
- linear array = 1D array
- Vector = 1D array
- My own research shows that tensor is a phrase used for arrays >= 3D; others say it is a generalization of scalars and vectors


In [1]:
non_homologous_array = [[4,2,3],
                        [5,1]]

matrix_and_array = [[4,2],
                    [5,1],
                    [8,2]]

#first level of this array is a list of three lists => 1st dimension is 3
#second level of this array is a list of two lists => 2nd dimension is 2
#third level of this array is a list of 4 integers => 3rd dimension is 4
lolol = [[[1,5,6,2],
          [3,2,1,3]],
         [[5,2,1,2],
           [6,4,8,4]],
         [[2,8,5,3],
           [1,1,9,4]]]
#array size is (3,2,4) => 3D array

Dot Product and Vector Addition
- Dot products between (2) vectors result in a scalar, a single value, because vectors are 1D
- Dot product of vectors is sum of the products of consecutive elements between two arrays
===> this is the operation needed to multiply weights and neuron inputs
- Vector addition is done element wise, each item in one vector is added to the same respective position in another vector 
====>this is how biases are added in

In [2]:
a = [1, 2, 3] #aka inputs to neurons
b = [2, 3, 4] #aka weights of neurons

dot_product = a[0]*b[0] + a[1]*b[1] + a[2]*b[2]
print(dot_product)

20


A Single Neuron with NumPy
- using dot products and vector addition to calculate final neuron output 

In [6]:
import numpy as np

inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2

outputs = np.dot(weights,inputs) + bias
print(outputs)

4.8


A Layer of Neurons with NumPy
- multiple neurons recieving same inputs (e.g., a layer)
- changes from a vector (1D) to a matrix (2D), because now have a list of list of weights => a set of weights for each Neuron in the layer
- Do the dot product of weights matrix and input vector => now results in a vector rather than scalar because multiple neurons result in multiple scalars. Vector size will be number of neurons, allows next bullet point below to work
- Add biases element wise to the resulting scalar

In [11]:
import numpy as np

inputs = [1.0, 2.0, 3.0, 2.5] #four inputs
weights = [[0.2, 0.8, -0.5, 1], #three neurons with four weights for each input
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]
biases = [2.0, 3.0, 0.5] #three biases for three neurons

#numpy automatically converts lists above to arrays
layer_outputs = np.dot(weights, inputs) + biases
#Matrix multiplication is a dot product of the first matrix's row and the second matrix's first column. 
#So because each row represents neuron weights in the weights matrix and we want to do the dot product
#of the weights and inputs, weights should be first inputs should be second. 
#also works because weights have matrix size (3,4) and inputs size is (4,), so row len matches col len

print(layer_outputs)

[4.8   1.21  2.385]


Batch Size
- Neural nets are typically trained in batches - or groups of multiple samples (or observations) of various features in a feature set
= sample = obeservation = feature set instance
= In my understanding: feature set => the independent variables/attributes/properties used to model the dependent variable
-Using small batch sizes causes the gradient updates/fitting aka convergence to bounce around because less samples are used to estimate gradient. Using more samples has a more direct convergence, but at the cost of: (1) more memory usage and (2) slow down associated with computing gradient for a greater number of samples

No code examples

Matrix Product
- Matrix product is the dot product of each matrix row and each matrix column, resulting in a matrix with the same dimensons as the number of rows in the first matrix and columns in the second matrix
- Requires that the first matrix have the same number of colunms as the second matrix does rows, so that the dot product works
- row/column vectors can be thought of as matrix with size of 1 for row/column, matrix product results in matrix of size 1,1



Transposition for the Matrix Product
- rotates matrix so that rows become columns and columns rows

In [19]:

#row vector - note without second set of brackets this would be a 1D array
np.array([[1,2,3]]) #has shape of (1,3) => if no second brackets shape would be (3,) 

#column vector- just transpose row vector
np.array([[1,2,3]]).T
#to construct column vector manually, would need to make a list of lists where each inner list consists of a single value


array([[1],
       [2],
       [3]])

In [20]:
import numpy as np

a = [1, 2, 3]
b = [2, 3, 4]

a = np.array([a]) #without second set of brackest these would be 1D
b = np.array([b]).T

print(np.dot(a, b)) #1,1 matrix returned

[[20]]


A Layer of Neurons & Batch of Data w/ NumPy
- previously were able to perform dot on single row of inputs and 3 sets of neuron weights because input was 1D vector
- when have a batch of inputs and multiple weights, where each input row represents a sample and each weight row represents a neuron's weights, cannot perform the matrix (dot) product directly on them => makes sense because, assuing inputs are first term and weights are second term and matrix are same shape, multiplying the row times the column would not be multiplying the neuron weights times the respective inputs. Instead would be treating each column as its own neuron, which is wrong and would result in the wrong output. => if matrix are not same shape wouldn't work either because there would be term mismatch
- solve this by transposing the weights matrix so that now the rows, which represented neurons, are now columns. So now dot product is operating on input row and weight.T column, giving us the sum of the weights time the inputs for each neuron. Resulting matrix will have each column representing the output of each neuron for a particular sample (input row), and each row corresponding to each input sample.
- keeping the output row oriented makes it easier to pass one layer's output as the input to the next layer => in other words, each input row aka sample corresponds to an output row of that sample transformed by the layer, so the output can be passed into the next layer using the same method
- bias 

In [22]:
import numpy as np

inputs = [[1.0, 2.0, 3.0, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]

weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2.0, 3.0, 0.5] #added to each row of output

layer_outputs = np.dot(inputs, np.array(weights).T) + biases

print(layer_outputs) 
#notice that as discussed before, the rows of the output correspond with the layer's output for that input, where each value in the row is a neurons output
#so the third value in the first row of the output is the third neuron's output of the first input (sample)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]
